package io.soos;

public interface PluginConstants {
    String DISPLAY_NAME = "SOOS SCA";
    String DESCRIPTION = "Scan your open source software for vulnerabilities and control the introduction of new dependencies";
    String TYPE = "SOOS-SCA";
    String FAIL_THE_BUILD = "fail_the_build";
    String INTEGRATION_NAME = "Teamcity";
    String SOOS_DIR_NAME = "soos";
    String EDIT_PARAMETERS_FILE_NAME = "editParameters.jsp";
    String WORKING_DIR = "teamcity.build.workingDir";
    String CHECKOUT_DIR = "teamcity.build.checkoutDir";
    String FILE_MODE = "a+x";
    String RUN_AND_WAIT_MODE_SELECTED = "run_and_wait mode selected, starting synchronous analysis...";
    String ASYNC_INIT_MODE_SELECTED = "async_init mode selected, starting asynchronous analysis...";
    String ASYNC_RESULT_MODE_SELECTED = "async_result mode selected, getting result from previous analysis...";
    Integer MIN_NUMBER_OF_CHARACTERS = 5;
    String PROPERTIES_FILE = "/teamcity.properties";
    String VERSION = "version";
    String ECHO_COMMAND = "echo";
    String CUSTOM_SCRIPT = "custom_script";
    String WIN_SCRIPT_EXT = ".bat";
    String UNIX_SCRIPT_EXT = ".sh";
    String REPORT_STATUS_URL = "reportStatusUrl";
    String STATUS = "status";
    String DEFAULT = "default";
    String DELIMITER_HYPHEN = " - ";
    String PARAMETERS = "Parameters: ";
    String SLASH = "/";
    String BACK_SLASH = "\\";
    String PIPE = " | ";
    String TEE_COMMAND = "tee ";
    String RESULT_FILE = "result.txt";
    String TEAMCITY_DATA_PATH_ENV = "TEAMCITY_DATA_PATH";
    String TEAMCITY_DATA_PATH = "teamcity.data.path";
    String TEAMCITY_BUILD_ID = "teamcity.agent.dotnet.build_id";
    String TEAMCITY_BUILD_TYPE_ID = "teamcity.buildType.id";
    String TEAMCITY_BUILD_CONF_NAME = "teamcity.buildConfName";
    String AGENT_HOME_DIR = "agent.home.dir";
    String TEAMCITY_STARTUP_PROPERTIES_FILE = "teamcity-startup.properties";
    String ARTIFACTS = "artifacts";
    String SYSTEM = "system";
    String CONFIG = "config";
    String CONF = "conf";
    String INTERNAL_PROPERTIES_FILE = "internal.properties";
    String CONTENT_POLICY_PROPERTY = "teamcity.web.header.Content-Security-Policy.protectedValue";
    String EQUAL = "=";
    String IMG_SRC_POLICY = "img-src 'self' data: blob: ";
    String SOOS_IMAGES_PRODUCTION_CDN = "http://cdn.mcauto-images-production.sendgrid.net/";
    String GREATER_THAN = " > ";
    String C_BACK_SLASH_COLON_DOUBLE_BACK_SLASH = "C\\:\\\\";
    String C_COLON_BACK_SLASH = "C:\\";
}
