name: SOOS SCA Scan
on: 
  push:
    branches: 
      - main 
jobs:
  synchronous-analysis-with-blocking-result:
    name: SOOS Scan
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Run SOOS - Scan for vulnerabilities
      uses: soos-io/soos-sca-github-action@v1.1.0
      with:
        project_name: "soos-sca-teamcity-plugin"
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
